### ISSUE TITLE
Skonfiguruj dokeryzację API

### ISSUE THREAD

**Issue by ZimmerPM** [Tomasz-Zdeb/Software-Engineering-Class-Project#41]
## Wymaganie wstępne
- [x] #23 

## Kryteria Akceptacji

- [x] Projekt zawiera konfigurację pozwalającą na uruchomienie API w kontenerze Dockerowym
- [x] Konfiguracja wykorzystuje `docker-compose.yml` w root directory projektu
- [x] Obraz został przetestowany
- [x] Użycie Dockera zostało opisane w dokumentacji

## Informacje
- Obraz powinien zawierać kompletny, działający projekt API
- Uruchomienie kontenera powinno pozwalać na kontakt z API
- `docker-compose.yml` znajduje się w root directory, ponieważ za jego pomocą powinno być możliwe uruchomienie całego projektu w taki sposób, aby komponenty mogły się ze sobą komunilować, przy użyciu jednego polecenia `docker-compose-up`

**Comment by wsliwa** [comment]
Dodałem PR z Dockerfilem #55.

Można też pomyśleć nad stworzeniem jakiegoś pliku docker-compose na przykład:

```
version: '3.4'
services:
  api:
    build:
      context: path/to/Dockerfile #podmienić
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: 1
```
